version: "3.9"

x-configs: &common_config
  restart: always
  env_file:
    - ./.env

services:
  django_admin:
    <<: *common_config
    build: ./admin
    volumes:
      - ./admin:/code
      - static_volume:/code/static
      - media_volume:/code/media
    command: /start.sh
    depends_on:
      db:
        condition: service_healthy

  websockets:
    <<: *common_config
    build:
      context: ws
      target: ${FASTAPI_ENV}
    volumes:
      - .:/app
    ports:
      - "8084:8084"
    depends_on:
      db:
        condition: service_healthy

  notification_service:
    container_name: notification_service
    build: ./notification_service
    <<: *common_config
    expose:
      - ${UVICORN_PORT}
    ports:
      - ${UVICORN_PORT}:${UVICORN_PORT}
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      django_admin:
        condition: service_started

  db:
    <<: *common_config
    image: ghcr.io/dbsystel/postgresql-partman:14
    container_name: db
    shm_size: 1g
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    <<: *common_config
    image: nginx:1.24
    volumes:
      - ./tmp/logs/nginx/:/var/log/nginx/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs/:/etc/nginx/conf.d/:ro
      - static_volume:/data/static:ro
      - media_volume:/data/media:ro
    depends_on:
      - django_admin
    ports:
      - "80:80"

  rabbitmq:
    <<: *common_config
    image: rabbitmq:3.10.7-management
    ports:
      - ${RABBITMQ_WEB_PORT}:${RABBITMQ_WEB_PORT}  # Management Web UI
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}    # AMQP protocol
    hostname: ${RABBITMQ_HOSTNAME}
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persist data
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/var/lib/redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  celery:
    build: ./admin
    volumes:
      - ./admin:/code
    command: celery -A core worker -l info --concurrency 4
    environment:
      - TZ=Asia/Almaty
    env_file:
      - ./.env
    depends_on:
      - django_admin
      - db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  celery-beat:
    build: ./admin
    volumes:
      - ./admin:/code
    command: celery -A core beat -l info
    environment:
      - TZ=Asia/Almaty
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  email:
    build: ./worker
    container_name: fastapi_app
    command: [ "sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port 8001" ]
    volumes:
      - .:/worker
    ports:
      - "8001:8001"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env

  worker:
    build: ./worker
    container_name: email_worker
    command: [ "python", "worker/worker.py" ]
    volumes:
      - .:/worker
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:
  static_volume:
  media_volume:
