# Generated by Django 5.1.1 on 2024-09-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtouser',
            name='retry_count',
            field=models.IntegerField(default=0, verbose_name='Количество повторных попыток'),
        ),
    ]
