# Generated by Django 5.1.1 on 2024-09-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationtouser_retry_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('personal', 'PERSONAL'), ('group', 'GROUP')], default='group', max_length=50, verbose_name='Тип рассылки'),
        ),
        migrations.AlterField(
            model_name='notificationtouser',
            name='status',
            field=models.CharField(choices=[('sent', 'SENT'), ('pending', 'PENDING'), ('failed', 'FAILED')], default='pending', max_length=10, verbose_name='Статус'),
        ),
    ]
