# Generated by Django 5.1.1 on 2024-09-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Повторяющееся'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recurrence_rule',
            field=models.CharField(blank=True, help_text="Введите crontab строку, например, '0 0 * * *' для ежедневной отправки в полночь.", max_length=100, null=True, verbose_name='Правило повторения (Crontab)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отправки'),
        ),
    ]
