# Generated by Django 5.1.1 on 2024-09-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_is_recurring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recurrence_rule',
            field=models.CharField(blank=True, default='* * * * *', help_text="Введите crontab строку, например, '0 0 * * *' для ежедневной отправки в полночь.", max_length=100, null=True, verbose_name='Правило повторения (Crontab)'),
        ),
    ]
