# Generated by Django 5.1.1 on 2024-10-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_recurrence_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='delivery_method',
            field=models.CharField(choices=[('email', 'EMAIL'), ('sms', 'SMS'), ('push', 'PUSH')], default='email', max_length=10, verbose_name='Способ доставки'),
        ),
    ]
