name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-html mypy wemake-python-styleguide
        pip install -r tests/unit/requirements.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8 and generate HTML report
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --format=html --htmldir=lint_report
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --format=html --htmldir=lint_report

    - name: Upload linter report
      uses: actions/upload-artifact@v3
      with:
        name: lint-report
        path: lint_report

    - name: Run mypy
      run: |
         mypy --explicit-package-bases . 

    - name: Test with pytest
      run: |
        pytest tests/unit -p no:warnings -s
    
    - name: Send success message to Telegram
      if: success()
      env:
        TELEGRAM_BOT_TOKEN: "6062792432:AAGJ4tGNHcwccBaXyZy7cfOjtxuHBsHOT1k"
        CHAT_ID: "964585805"
      run: |
        curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
             -d "chat_id=$CHAT_ID&text=CI%20passed%20for%20pull%20request%20#${{ github.event.number }}%20on%20branch%20${{ github.head_ref }}"

    - name: Send failure message to Telegram
      if: failure()
      env:
        TELEGRAM_BOT_TOKEN: "6062792432:AAGJ4tGNHcwccBaXyZy7cfOjtxuHBsHOT1k"
        CHAT_ID: "964585805"
      run: |
        curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
             -d "chat_id=$CHAT_ID&text=CI%20failed%20for%20pull%20request%20#${{ github.event.number }}%20on%20branch%20${{ github.head_ref }}"
